### ISSUE TITLE
flutter run is warming

### ISSUE THREAD

**Issue by Burak0853** [JiangJuHong/FlutterClipboardListener#3]
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':clipboard_listener' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.50

**Comment by JiangJuHong** [comment]
`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.`

**Comment by Burak0853** [comment]
I updated the gradle version in the package and it worked fine, thank you.
